### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by jsturdy**
Possible update for `.gitignore`, as per #22 

## Description
Tries to be sensible as to what is necessary for the package, and what is generated/used only locally

### Types of changes
- [x] Maintenance (Routine cleanup for maintainability)

## How Has This Been Tested?
Untested, not related to code itself

### CODE REVIEW

**Comment by jsturdy** [comment]
If this needs to be switched to a PR to `develop` let me know, it's should be straightforward to modify, as nothing comes in from `master` to `develop` at the current snapshot

**Comment by mexanick** [comment]
@jsturdy yeah, please change the PR to develop. We will merge it to the master branch later.

**Review by mexanick — CHANGES_REQUESTED** [review]
@jsturdy yeah, please change the PR to develop. We will merge it to the master branch later.

**Review by mexanick — APPROVED** [review]

**Comment by mexanick** [comment]
I actually found how I can do it myself =)

**Pull request merged**
