### PR TITLE
Modifying the parsers to handle xi:include

### LINKED ISSUE #34: Feature Request: Parse Two XML Address Tables Instead of One
## Brief summary of issue

The CTP7 and OHv3a each have their own xml file which defines the address table.  See for example:

https://github.com/evka85/GEM_AMC/releases/tag/v3.2.6
https://github.com/andrewpeck/OptoHybridv3/releases/tag/3.0.7.A

Right now for the XML to be parsed you have to copy/paste the OHv3a xml into the CTP7 xml which is a bit tedious.

Would like that `parseXML()` is changed to work with two files instead of one.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [X] Feature request (request for change which adds functionality)

## Expected Behavior

Simply making the links (e.g. `gem_amc_top.xml` and `gem_oh_top.xml`) for the two xml's in the appropriate location `parseXML()` should use both of them.

If `gem_oh_top.xml` is not found it should print a warning but continue parsing the xml to be backwards compatible with older FW versions/v2b electronics.

## Current Behavior

You have to copy/paste the OHv3a xml into the CTP7 xml.

## Context (for feature requests)

Quality of life improvement.

### PR DESCRIPTION
**Pull request by mexanick**
## Description

Both python and C++ XML parsers are updated to handle the xi:include to link optohybrid_registers.xml address table. Python parser changed to lxml, C++ is changed to DOMLSParser.
Now in order to include the optohybrid nodes into the gem_amc_top.xml one need to:

- modify the `<node id="top">` node to be like: 
`<node id="top" xmlns:xi="http://www.w3.org/2001/XInclude">`

-  insert a following line in the `OH${OH_IDX}` node just before the `GEB` node:
`<xi:include href="optohybrid_registers.xml"/>`

The resulting part of xml should look like this:
```
     <node id="OH${OH_IDX}"  address="0x0"
            description="Optohybrid ${OH_IDX}"
            generate="true" generate_size="2" generate_address_step="0x00010000" generate_idx_var="OH_IDX">

        <!--Insert here the OH FPGA module -->
        <xi:include href="optohybrid_registers.xml"/>

        <node id="GEB"  address="0x100000"
              description="VFAT3 registers">
```

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Fixes https://github.com/cms-gem-daq-project/xhal/issues/34

## How Has This Been Tested?

Tested with `reg_interface` and C++ unit tests
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bdorney** [comment]
> Now in order to include the optohybrid nodes into the gem_amc_top.xml one need to:

> modify the <node id="top"> node to be like:
<node id="top" xmlns:xi="http://www.w3.org/2001/XInclude">

>insert a following line in the OH${OH_IDX} node just before the GEB node:
><xi:include href="optohybrid_registers.xml"/>

>The resulting part of xml should look like this:

>    <node id="OH${OH_IDX}"  address="0x0"
>            description="Optohybrid ${OH_IDX}"
>            generate="true" generate_size="2" generate_address_step="0x00010000" >generate_idx_var="OH_IDX">

>        
>        <xi:include href="optohybrid_registers.xml"/>

>        <node id="GEB"  address="0x100000"
>              description="VFAT3 registers">

This is something the user should do every-time, or can it be something changed for the xml generated in the FW release? @evka85?

**Comment by bdorney** [comment]
And could you include your example xml's that show this with this PR, or maybe attached to an elog somewhere?

**Comment by mexanick** [comment]
The XML maintenance should be provided by @evka85 I believe =)
Considering an example of my XML - see [here](https://drive.google.com/drive/folders/1Q0E4zvxkNbhPf7GqSo-XUMEsE0ezAnfY?usp=sharing)

**Comment by jsturdy** [comment]
* Consider extending evka85/GEM_AMC#15 to add this request, as it pertains (partially) to the address table changes
* Also add a target which we can link to a milestone (maybe just a project on the projects board) in `cmsgemos`/`vfatqc-python-scripts`/`ctp7_modules`/`GEM_AMC`/`OptoHybridv3` (any other deps?) to ensure that we have compatibility between versions

**Review by bdorney — APPROVED** [review]

**Pull request merged**
