### PR TITLE
Updating sbitRateScan to comply with ctp7_modules PR #102

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Requires:

https://github.com/cms-gem-daq-project/ctp7_modules/pull/102

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Multi link sbit rate scan; significantly reduces time needed to scan all OH's on a CTP7.

## How Has This Been Tested?

See discussion in:

https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/231

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by mexanick — DISMISSED** [review]

**Review by jsturdy — APPROVED** [review]
Cursory

**Review by jsturdy — DISMISSED** [review]
Cursory

**Comment by jsturdy** [comment]
@bdorney needs `rebase`

**Comment by bdorney** [comment]
rebased

**Review by jsturdy — APPROVED** [review]

**Review by mexanick — APPROVED** [review]
cursory

**Pull request merged**
