### PR TITLE
New Feature: Programming GBTs over fiber link

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Adding @evka85's script for programming the GBTs over the fiber link.  Note a GBT must be minimally fused to lock to the fiber link for this to work and `GBT_READY` must be `0x1`.  Also the `I2C` jumper on the OH for the GBT of interest must have been removed.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Program GBTs over the fiber link.

## How Has This Been Tested?

Extensively during the v3 electronics testing before and after the ESR.

### CODE REVIEW

**Comment by mexanick** [comment]
do we want this functionality to be available only from CTP7, or from host PC as well?

**Review by mexanick — CHANGES_REQUESTED** [review]
I think this PR will benefit from a little refactoring. In general, the code is very well written and the only down side is that the `main` function is supposed to be called from shell. Instead, we need to have options parser involved to maintain a standalone use case and rename `main` to smth like `programGBT` which will take all needed inputs as function arguments.

**Comment by bdorney** [comment]
> do we want this functionality to be available only from CTP7, or from host PC as well?

Not really sure what @evka85's original idea was.  This was his script.  I'm including it so we can have it for the gemctp7user repo.

> I think this PR will benefit from a little refactoring. In general, the code is very well written and the only down side is that the main function is supposed to be called from shell. Instead, we need to have options parser involved to maintain a standalone use case and rename main to smth like programGBT which will take all needed inputs as function arguments.

I'll take a look to see how quickly that can be implemented.

**Comment by bdorney** [comment]
`main()` has been changed to `programGBT(...)` with arguments.  The syntax of the command has remained unchanged.

**Review by mexanick — APPROVED** [review]

**Pull request merged**
